server:
  port: 9999
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: mizhuo809@foxmail.com
    password: ngqyrjmaoqygijdg
    port: 587
    properties:
      mail:
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  rabbitmq:
    username: admin
    password: admin
    host: localhost
    port: 5672